import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  pack: {
    entry: ["napi/src/vite.ts"],
    dts: { tsgo: true },
    format: "esm",
    outDir: "napi/dist",
    inputOptions: {
      external: ["@oxc-plugin-react-compiler/binding", "vite"],
    },
    deps: {
      onlyBundle: false,
    },
  },
  test: {
    include: ['tests/**/*.test.ts'],
  },
  fmt: {
    ignorePatterns: ["third_party/**"],
    arrowParens: "avoid",
    singleQuote: true,
    jsxSingleQuote: true,
    arrowParentheses: "as-needed",
    lineEnding: "lf",
    printWidth: 160,
    experimentalSortImports: {
      order: "asc",
      groups: [
        ["type"],
        ["builtin"],
        ["external"],
        ["subpath", "internal"],
        ["parent"],
        ["sibling"],
        ["index"],
      ],
    },
  },
  lint: {
    ignorePatterns: ["third_party/**", "tests/fixtures/**"],
    plugins: [
      "eslint",
      "typescript",
      "unicorn",
      "oxc",
      "import",
      "react",
      "react-perf",
      "jsx-a11y",
      "vitest",
    ],
    settings: {
      vitest: {
        typecheck: true,
      },
    },
    rules: {
      "array-callback-return": [
        "error",
        {
          checkForEach: true,
        },
      ],
      "arrow-body-style": ["error", "as-needed"],
      "block-scoped-var": "error",
      "default-case-last": "error",
      eqeqeq: "error",
      "func-style": [
        "error",
        "expression",
        {
          allowArrowFunctions: true,
        },
      ],
      "guard-for-in": "error",
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-await-in-loop": "error",
      "no-bitwise": [
        "error",
        {
          allow: ["~"],
          int32Hint: true,
        },
      ],
      "no-case-declarations": "error",
      "no-constructor-return": "error",
      "no-div-regex": "error",
      "no-else-return": "error",
      "no-empty": "error",
      "no-eq-null": "error",
      "node/no-exports-assign": "error",
      "no-extend-native": "error",
      "no-extra-label": "error",
      "no-fallthrough": "error",
      "no-iterator": "error",
      "no-label-var": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "no-misleading-character-class": "error",
      "no-multi-assign": "error",
      "no-multi-str": "error",
      "no-negated-condition": "error",
      "no-new-func": "error",
      "node/no-new-require": "error",
      "no-new-wrappers": "error",
      "no-object-constructor": "error",
      "no-param-reassign": "error",
      "no-promise-executor-return": "error",
      "no-proto": "error",
      "no-redeclare": "error",
      "no-regex-spaces": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-template-curly-in-string": "error",
      "no-throw-literal": "error",
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "operator-assignment": "error",
      "prefer-const": "error",
      "prefer-destructuring": "error",
      "prefer-exponentiation-operator": "error",
      "prefer-numeric-literals": "error",
      "prefer-object-has-own": "error",
      "prefer-object-spread": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "preserve-caught-error": "error",
      radix: "error",
      "symbol-description": "error",
      yoda: "error",
      "unicorn/catch-error-name": "error",
      "unicorn/consistent-assert": "error",
      "unicorn/consistent-date-clone": "error",
      "unicorn/consistent-empty-array-spread": "error",
      "unicorn/consistent-existence-index-check": "error",
      "unicorn/consistent-function-scoping": "error",
      "unicorn/empty-brace-spaces": "error",
      "unicorn/error-message": "error",
      "unicorn/escape-case": "error",
      "unicorn/filename-case": [
        "error",
        {
          cases: {
            camelCase: true,
            kebabCase: true,
          },
        },
      ],
      "unicorn/new-for-builtins": "error",
      "unicorn/no-abusive-eslint-disable": "error",
      "unicorn/no-accessor-recursion": "error",
      "unicorn/no-array-callback-reference": "error",
      "unicorn/no-array-for-each": "error",
      "unicorn/no-array-method-this-argument": "error",
      "unicorn/no-array-reduce": "error",
      "unicorn/no-array-reverse": "error",
      "unicorn/no-array-sort": "error",
      "unicorn/no-await-expression-member": "error",
      "unicorn/no-console-spaces": "error",
      "unicorn/no-document-cookie": "error",
      "unicorn/no-hex-escape": "error",
      "unicorn/no-immediate-mutation": "error",
      "unicorn/no-instanceof-array": "error",
      "unicorn/no-instanceof-builtins": "error",
      "unicorn/no-length-as-slice-end": "error",
      "unicorn/no-magic-array-flat-depth": "error",
      "unicorn/no-negation-in-equality-check": "error",
      "unicorn/no-new-buffer": "error",
      "unicorn/no-static-only-class": "error",
      "unicorn/no-this-assignment": "error",
      "unicorn/no-typeof-undefined": "error",
      "unicorn/no-unnecessary-array-flat-depth": "error",
      "unicorn/no-unnecessary-array-splice-count": "error",
      "unicorn/no-unnecessary-slice-end": "error",
      "unicorn/no-useless-collection-argument": "error",
      "unicorn/no-useless-error-capture-stack-trace": "error",
      "unicorn/no-useless-promise-resolve-reject": "error",
      "unicorn/no-useless-switch-case": "error",
      "unicorn/no-useless-undefined": "error",
      "unicorn/no-zero-fractions": "error",
      "unicorn/number-literal-case": "error",
      "unicorn/numeric-separators-style": [
        "error",
        {
          onlyIfContainsSeparator: true,
        },
      ],
      "unicorn/prefer-array-find": "error",
      "unicorn/prefer-array-flat": "error",
      "unicorn/prefer-array-flat-map": "error",
      "unicorn/prefer-array-index-of": "error",
      "unicorn/prefer-array-some": "error",
      "unicorn/prefer-at": "error",
      "unicorn/prefer-bigint-literals": "error",
      "unicorn/prefer-blob-reading-methods": "error",
      "unicorn/prefer-class-fields": "error",
      "unicorn/prefer-classlist-toggle": "error",
      "unicorn/prefer-code-point": "error",
      "unicorn/prefer-date-now": "error",
      "unicorn/prefer-default-parameters": "error",
      "unicorn/prefer-dom-node-append": "error",
      "unicorn/prefer-dom-node-dataset": "error",
      "unicorn/prefer-dom-node-remove": "error",
      "unicorn/prefer-dom-node-text-content": "error",
      "unicorn/prefer-global-this": "error",
      "unicorn/prefer-keyboard-event-key": "error",
      "unicorn/prefer-logical-operator-over-ternary": "error",
      "unicorn/prefer-math-min-max": "error",
      "unicorn/prefer-math-trunc": "error",
      "unicorn/prefer-modern-dom-apis": "error",
      "unicorn/prefer-modern-math-apis": "error",
      "unicorn/prefer-native-coercion-functions": "error",
      "unicorn/prefer-negative-index": "error",
      "unicorn/prefer-node-protocol": "error",
      "unicorn/prefer-number-properties": "error",
      "unicorn/prefer-object-from-entries": "error",
      "unicorn/prefer-optional-catch-binding": "error",
      "unicorn/prefer-query-selector": "error",
      "unicorn/prefer-reflect-apply": "error",
      "unicorn/prefer-regexp-test": "error",
      "unicorn/prefer-response-static-json": "error",
      "unicorn/prefer-set-has": "error",
      "unicorn/prefer-set-size": "error",
      "unicorn/prefer-string-raw": "error",
      "unicorn/prefer-string-replace-all": "error",
      "unicorn/prefer-string-slice": "error",
      "unicorn/prefer-string-trim-start-end": "error",
      "unicorn/prefer-structured-clone": "error",
      "unicorn/prefer-top-level-await": "error",
      "unicorn/prefer-type-error": "error",
      "unicorn/require-array-join-separator": "error",
      "unicorn/require-module-attributes": "error",
      "unicorn/require-module-specifiers": "error",
      "unicorn/require-number-to-fixed-digits-argument": "error",
      "unicorn/require-post-message-target-origin": "error",
      "unicorn/text-encoding-identifier-case": "error",
      "unicorn/throw-new-error": "error",
      "eslint/sort-imports": [
        "error",
        {
          allowSeparatedGroups: true,
          ignoreDeclarationSort: true,
        },
      ],
      "oxc/approx-constant": "error",
      "oxc/bad-bitwise-operator": "error",
      "oxc/branches-sharing-code": "error",
      "oxc/misrefactored-assign-op": "error",
      "oxc/no-accumulating-spread": "error",
      "oxc/no-barrel-file": "error",
      "oxc/no-const-enum": "error",
      "oxc/no-map-spread": "error",
      "oxc/no-this-in-exported-function": "error",
      "typescript/array-type": "error",
      "typescript/ban-ts-comment": [
        "error",
        {
          "ts-ignore": "allow-with-description",
        },
      ],
      "typescript/ban-types": "error",
      "typescript/consistent-generic-constructors": "error",
      "typescript/consistent-indexed-object-style": "error",
      "typescript/consistent-type-definitions": "error",
      "typescript/consistent-type-imports": "error",
      "typescript/no-confusing-non-null-assertion": "error",
      "typescript/no-confusing-void-expression": "error",
      "typescript/no-deprecated": "error",
      "typescript/no-dynamic-delete": "error",
      "typescript/no-empty-interface": "error",
      "typescript/no-empty-object-type": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-extraneous-class": "error",
      "typescript/no-import-type-side-effects": "error",
      "typescript/no-inferrable-types": "error",
      "typescript/no-misused-promises": "error",
      "typescript/no-non-null-asserted-nullish-coalescing": "error",
      "typescript/no-non-null-assertion": "error",
      "typescript/no-require-imports": "error",
      "typescript/no-unnecessary-boolean-literal-compare": "error",
      "typescript/no-unnecessary-template-expression": "error",
      "typescript/no-unnecessary-type-arguments": "error",
      "typescript/no-unnecessary-type-assertion": "error",
      "typescript/no-unnecessary-type-constraint": "error",
      "typescript/no-unsafe-argument": "error",
      "typescript/no-unsafe-assignment": "error",
      "typescript/no-unsafe-call": "error",
      "typescript/no-unsafe-enum-comparison": "error",
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-unsafe-member-access": [
        "error",
        {
          allowOptionalChaining: true,
        },
      ],
      "typescript/no-unsafe-return": "error",
      "typescript/no-unsafe-type-assertion": "error",
      "typescript/no-var-requires": "error",
      "typescript/prefer-for-of": "error",
      "typescript/prefer-function-type": "error",
      "typescript/prefer-includes": "error",
      "typescript/prefer-namespace-keyword": "error",
      "typescript/prefer-nullish-coalescing": "error",
      "typescript/prefer-optional-chain": "error",
      "typescript/prefer-promise-reject-errors": "error",
      "typescript/prefer-reduce-type-parameter": "error",
      "typescript/prefer-return-this-type": "error",
      "typescript/prefer-ts-expect-error": "error",
      "typescript/related-getter-setter-pairs": "error",
      "typescript/require-await": "error",
      "typescript/restrict-plus-operands": "error",
      "typescript/return-await": ["error", "error-handling-correctness-only"],
      "typescript/strict-boolean-expressions": [
        "error",
        {
          allowNullableString: true,
        },
      ],
      "typescript/switch-exhaustiveness-check": "error",
      "typescript/use-unknown-in-catch-callback-variable": "error",
      "import/consistent-type-specifier-style": "error",
      "import/first": "error",
      "import/no-commonjs": "error",
      "import/no-mutable-exports": "error",
      "import/no-named-as-default-member": "error",
      "import/no-named-default": "error",
      "import/no-self-import": "error",
      "import/no-unassigned-import": [
        "error",
        {
          allow: ["**/*.css", "@total-typescript/ts-reset"],
        },
      ],
      "promise/always-return": "error",
      "promise/no-callback-in-promise": "error",
      "promise/no-multiple-resolved": "error",
      "promise/no-nesting": "error",
      "promise/no-new-statics": "error",
      "promise/no-return-in-finally": "error",
      "promise/no-return-wrap": "error",
      "promise/param-names": "error",
      "promise/prefer-await-to-callbacks": "error",
      "promise/prefer-await-to-then": "error",
      "promise/prefer-catch": "error",
      "promise/spec-only": "error",
      "promise/valid-params": "error",
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
});
